
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 07 00:51:06 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MONKEY = 52;
  public static final int RPARENT = 43;
  public static final int LPARENT = 42;
  public static final int PLUSPLUS = 36;
  public static final int LBRACKET = 44;
  public static final int CONST = 6;
  public static final int SEMI = 38;
  public static final int CONTINUE = 15;
  public static final int LESS = 31;
  public static final int MINUS = 23;
  public static final int GRE = 29;
  public static final int AND = 33;
  public static final int LESSEQUAL = 32;
  public static final int OR = 34;
  public static final int COMMA = 40;
  public static final int CLASS = 3;
  public static final int DOTDOT = 39;
  public static final int DIV = 25;
  public static final int PLUS = 22;
  public static final int IF = 7;
  public static final int THIS = 20;
  public static final int DOT = 41;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 37;
  public static final int RETURN = 12;
  public static final int RBRACKET = 45;
  public static final int EQUAL = 35;
  public static final int NEW = 10;
  public static final int error = 1;
  public static final int ISEQUAL = 27;
  public static final int MUL = 24;
  public static final int NUMBER = 16;
  public static final int MOD = 26;
  public static final int BREAK = 48;
  public static final int IDENT = 17;
  public static final int VOID = 13;
  public static final int ISNOTEQUAL = 28;
  public static final int FOREACH = 21;
  public static final int LBRACE = 46;
  public static final int ELSE = 5;
  public static final int READ = 49;
  public static final int ENUM = 4;
  public static final int GOTO = 51;
  public static final int CHARCONST = 19;
  public static final int WHILE = 9;
  public static final int RBRACE = 47;
  public static final int BOOLCONST = 18;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int GREEQUAL = 30;
  public static final int PRINT = 11;
  public static final int DO = 8;
  public static final int HENCE = 50;
}

